Modified SalesforceClient, HttpClient and API default version.
clamidity/SalesforceMagic pull request #29
Opened 2017-02-22 15:08 UTC by lventre

**SalesforceClient**: used SecurityProtocolType.Tls12 as TLS 1.0 is not accepted anymore by Salesforce.
**HttpClient**: removed several using blocks that swallow exception traces + implemented IDisposable pattern.
Soap and Bulk request managers: **API default version** set to 38.0.

2017-02-22 15:25 UTC, lventre commented
Michael,

This is my first pull request, so I hope I'm doing it well.

My first update is because TLS 1.0 not allowed anymore by Salesforce, so I replaced it by TLS 1.2.
I also updated the HttpClient classe because the PerformRequest method threw a NullReferenceException.  I had to remove using blocks  to retrieve the exception trace. I also took the opportunity to implement the IDisposable pattern.

Thank you for your great library!
Loïc

2017-02-23 18:02 UTC, michael-shattuck requested changes
Thank you for the pull request. I added a comment to the implementation of IDisposable. If you could remove the items mentioned I'll merge it in. Awesome work!

2017-02-23 18:02 UTC, michael-shattuck commented on SalesforceMagic/Http/HttpClient.cs
> +            //
Let's remove these comments and the extra if statement for now. If we need it in the future we can add it back.

2017-02-24 18:36 UTC, lventre commented
Hello,

I removed to unnecessary comments in HttpClient as requested.
I also found valuable to define one's own security protocol when using the library. Hence I added a new argument to SalesforceClient with a default value to have no impact on existing code (adding this argument to the Login method would have impacts on GetSession and GetSessionId methods too).

Looking forward to hearing from you,
Loïc

2017-02-25 05:52 UTC, michael-shattuck commented
This looks great thank you

2017-02-25 05:52 UTC, merged